/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Informacion.AproxVoguel;
import Informacion.CostMinim;
import Informacion.EsqNoroeste;
import Informacion.Simplex;

/**
 *
 * @author mrdan
 */
public class Didactico extends javax.swing.JFrame {

    /**
     * Creates new form Didactico
     */
    public Didactico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnEsqNo = new javax.swing.JButton();
        jbtnCosMin = new javax.swing.JButton();
        jbtnVoguel = new javax.swing.JButton();
        jbtnSimplex = new javax.swing.JButton();
        jbtnInicio = new javax.swing.JButton();
        jbtnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 250));

        jbtnEsqNo.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jbtnEsqNo.setText("MÉTODO DE LA ESQUINA NOROESTE");
        jbtnEsqNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OnClick(evt);
            }
        });
        jbtnEsqNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEsqNoActionPerformed(evt);
            }
        });

        jbtnCosMin.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jbtnCosMin.setText("MÉTODO DEL COSTO MÍNIMO");
        jbtnCosMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OnClick(evt);
            }
        });

        jbtnVoguel.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jbtnVoguel.setText("MÉTODO DE APROXIMACIÓN DE VOGEL");
        jbtnVoguel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OnClick(evt);
            }
        });

        jbtnSimplex.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jbtnSimplex.setText("MÉTODO SIMPLEX");
        jbtnSimplex.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OnClick(evt);
            }
        });

        jbtnInicio.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jbtnInicio.setText("INICIO");
        jbtnInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OnClick(evt);
            }
        });

        jbtnSalir.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jbtnSalir.setText("SALIR");
        jbtnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OnClick(evt);
            }
        });
        jbtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnEsqNo)
                    .addComponent(jbtnCosMin)
                    .addComponent(jbtnVoguel)
                    .addComponent(jbtnSimplex))
                .addContainerGap(319, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnSalir)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnEsqNo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnCosMin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnVoguel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnSimplex)
                .addGap(39, 209, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnSalir)
                    .addComponent(jbtnInicio))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnEsqNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEsqNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnEsqNoActionPerformed

    private void jbtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnSalirActionPerformed

    private void OnClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OnClick
        // TODO add your handling code here:
        if(evt.getSource() == jbtnInicio){
            new Inicio().setVisible(true);
            this.dispose();
        } else if(evt.getSource() == jbtnEsqNo){
            new EsqNoroeste().setVisible(true);
            this.dispose();
        } else if(evt.getSource() == jbtnCosMin){
            new CostMinim().setVisible(true);
            this.dispose();
        } else if(evt.getSource() == jbtnSimplex){
            new Simplex().setVisible(true);
            this.dispose();
        } else if(evt.getSource() == jbtnVoguel){
            new AproxVoguel().setVisible(true);
            this.dispose();
        } else if(evt.getSource() == jbtnSalir)
            System.exit(0);
    }//GEN-LAST:event_OnClick

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Didactico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Didactico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Didactico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Didactico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Didactico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnCosMin;
    private javax.swing.JButton jbtnEsqNo;
    private javax.swing.JButton jbtnInicio;
    private javax.swing.JButton jbtnSalir;
    private javax.swing.JButton jbtnSimplex;
    private javax.swing.JButton jbtnVoguel;
    // End of variables declaration//GEN-END:variables
}
