/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import MetodoSimplex.AproximarNumero;
import MetodoSimplex.GetX;
import Tablas.EscribirLeer;
import Tablas.TablaSimplex;
import MetodoSimplex.MetodoSimplex;
import static MetodoSimplex.MetodoSimplex.columnaMayor;
import static MetodoSimplex.MetodoSimplex.filaMenor;
import static MetodoSimplex.MetodoSimplex.pivote;
import static MetodoSimplex.MetodoSimplex.todosMenor;
import java.awt.Component;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableColumn;

/**
 *
 * @author David
 */
public class MSimplex extends javax.swing.JFrame {

    /**
     * Creates new form MSimplex
     */
    
    private FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos simpx ", "simpx");
    private DefaultTableModel modRest = null;
    private DefaultTableModel modSolu = null;
    
    private int iX = 0;
    private int iNoRest;
    private boolean bLimpiar = true;
    private boolean bGuardar = true;
    private EscribirLeer archivo = new EscribirLeer(); 
    
    public MSimplex() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Datos = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jcbMaxMin = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jspVar = new javax.swing.JSpinner();
        jspRest = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jbtnOk = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtblRest = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jbtnContinuar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblTabla = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaOp = new javax.swing.JTextArea();
        jlblPivote = new javax.swing.JLabel();
        jlblFila = new javax.swing.JLabel();
        jlblColumna = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtxtarModMat = new javax.swing.JTextArea();
        jlblModMat = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jbtnInDat = new javax.swing.JButton();
        jbtnSolucion = new javax.swing.JButton();
        jbtnSolPasoAPaso = new javax.swing.JButton();
        jbtnSalir = new javax.swing.JButton();
        jbtnInicio = new javax.swing.JButton();

        jcbMaxMin.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jcbMaxMin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Maximizar", "Minimizar" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jcbMaxMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jcbMaxMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jspVar.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N

        jspRest.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jspRest.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jspRestStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabel1.setText("Variables");

        jLabel2.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabel2.setText("Restricciones");

        jbtnOk.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jbtnOk.setText("OK");
        jbtnOk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OnClick(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(40, 40, 40))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(15, 15, 15)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jspRest, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addComponent(jspVar))
                .addGap(18, 18, 18)
                .addComponent(jbtnOk)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jspVar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jspRest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jbtnOk))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Coeficientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gadugi", 1, 14))); // NOI18N
        jPanel6.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N

        jtblRest.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jtblRest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtblRest.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtblRestKeyTyped(evt);
            }
        });
        jScrollPane4.setViewportView(jtblRest);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                .addContainerGap())
        );

        jbtnContinuar.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jbtnContinuar.setText("CONTINUAR");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnContinuar)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnContinuar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout DatosLayout = new javax.swing.GroupLayout(Datos.getContentPane());
        Datos.getContentPane().setLayout(DatosLayout);
        DatosLayout.setHorizontalGroup(
            DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DatosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        DatosLayout.setVerticalGroup(
            DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jtblTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtblTabla);

        jtaOp.setBackground(new java.awt.Color(240, 240, 240));
        jtaOp.setColumns(20);
        jtaOp.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        jtaOp.setRows(5);
        jScrollPane2.setViewportView(jtaOp);

        jlblPivote.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        jlblPivote.setText("Pivote");

        jlblFila.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        jlblFila.setText("Fila");

        jlblColumna.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        jlblColumna.setText("Columna");

        jtxtarModMat.setBackground(new java.awt.Color(240, 240, 240));
        jtxtarModMat.setColumns(20);
        jtxtarModMat.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        jtxtarModMat.setRows(5);
        jScrollPane3.setViewportView(jtxtarModMat);

        jlblModMat.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        jlblModMat.setText("Modelo Matemático:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                    .addComponent(jlblModMat)
                    .addComponent(jlblPivote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblFila, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblColumna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlblPivote)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlblFila)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlblColumna)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlblModMat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jbtnInDat.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jbtnInDat.setText("INSERTAR DATOS");
        jbtnInDat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OnClick(evt);
            }
        });

        jbtnSolucion.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jbtnSolucion.setText("SOLUCIÓN");
        jbtnSolucion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OnClick(evt);
            }
        });

        jbtnSolPasoAPaso.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jbtnSolPasoAPaso.setText("SOLUCIÓN PASO A PASO");
        jbtnSolPasoAPaso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OnClick(evt);
                Click(evt);
            }
        });

        jbtnSalir.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jbtnSalir.setText("SALIR");
        jbtnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OnClick(evt);
            }
        });

        jbtnInicio.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jbtnInicio.setText("INICIO");
        jbtnInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OnClick(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jbtnInDat, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jbtnSolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jbtnSolPasoAPaso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnSolucion)
                    .addComponent(jbtnInDat)
                    .addComponent(jbtnSolPasoAPaso)
                    .addComponent(jbtnSalir)
                    .addComponent(jbtnInicio))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OnClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OnClick
        if(evt.getSource() == jbtnInDat){
            Datos.setBounds(this.getX() + 100, this.getY() + 5, Datos.getWidth(), Datos.getHeight());
            Datos.setVisible(true);
            if (bLimpiar)
                tablaRestricciones();
            bLimpiar = false;
            jbtnSolPasoAPaso.setEnabled(false);
            iNoRest = modRest.getRowCount()-1;
        } else if(evt.getSource() == jbtnInicio){
            new Inicio().setVisible(true);
            this.dispose();
        } else if(evt.getSource() == jbtnSalir)
            System.exit(0);
        else if(evt.getSource() == jbtnOk)
            tablaRestricciones();
        else if(evt.getSource() == jbtnContinuar){
            if (!validar()){
                TablaSimplex.TablaSolucion(iX, iNoRest, modRest, jtblTabla);
                modSolu = (DefaultTableModel) jtblTabla.getModel();
                MetodoSimplex.calcularZj(modSolu);
                MetodoSimplex.calcularCj_Zj(modSolu);
                if (jcbMaxMin.getSelectedIndex() == 0)
                    MetodoSimplex.mayorFilaCj_Zj(modSolu);
                else
                    MetodoSimplex.menorFilaCj_Zj(modSolu);
                MetodoSimplex.CalcularXn_Mayor(modSolu);
                MetodoSimplex.menor(modSolu);
                jbtnSolucion.setEnabled(true);
                jbtnSolPasoAPaso.setEnabled(true);
                Datos.setVisible(false);
                MetodoSimplex.numeroTablones = 1;
                jtxtarModMat.setText(null);
                jlblFila.setText("Fila: " + (filaMenor - 1));
                jlblColumna.setText("Columna: " + (columnaMayor));
                jlblPivote.setText("Pivote: " + pivote);
                jlblPivote.setText("Pivote: " + AproximarNumero.valorAproximado
        (String.valueOf(modSolu.getValueAt(filaMenor, columnaMayor))));
                ecuaciones();
            }
        } else if(evt.getSource() == jbtnSolucion){
            while(!todosMenor  && filaMenor > 0){
                Click(evt);
            }
            jbtnSolucion.setEnabled(false);
            limpiarUltimaCelda();
        }
    }//GEN-LAST:event_OnClick

    private void jspRestStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jspRestStateChanged
        int row = Integer.parseInt(jspRest.getValue().toString());
        String g[] = new String[iX];
        if(row > iNoRest){
            for(int i = iNoRest + 1; i <= row; i++){
                //g[0] = "Rest " + i;
                modRest.addRow(g);
                modRest.setValueAt("<=", i, modRest.getColumnCount() - 2);
            }
            iNoRest = row;
        } else if(row < iNoRest){
            while (iNoRest != row){
                modRest.removeRow(iNoRest);
                iNoRest--;
            }
        }
    }//GEN-LAST:event_jspRestStateChanged

    private void jtblRestKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtblRestKeyTyped
        char a = evt.getKeyChar();
        if(!Character.isDigit(a) && a != '-' && a != 'E' && a != '.'){
            evt.consume();
        }
    }//GEN-LAST:event_jtblRestKeyTyped

    private void Click(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Click
        if(!MetodoSimplex.todosMenor){
                if(MetodoSimplex.filaMenor <= 0)
                    JOptionPane.showMessageDialog(this, "No se ha podido encontrar una solución al sistema.");
                else{
                    MetodoSimplex.Convertir0Pivote(modSolu);
                    MetodoSimplex.Gauss(modSolu);
                    MetodoSimplex.calcularZj(modSolu);
                    MetodoSimplex.calcularCj_Zj(modSolu);
                    if(jcbMaxMin.getSelectedItem().toString().equalsIgnoreCase("Maximizar"))
                        MetodoSimplex.mayorFilaCj_Zj(modSolu);
                    else if(jcbMaxMin.getSelectedItem().toString().equalsIgnoreCase("Minimizar"))
                        MetodoSimplex.menorFilaCj_Zj(modSolu);
                    MetodoSimplex.CalcularXn_Mayor(modSolu);
                    MetodoSimplex.menor(modSolu);
                }
            }
            if(MetodoSimplex.todosMenor){
                jbtnSolPasoAPaso.setEnabled(false);
                GetX.mostar(modSolu, iX);
                limpiarUltimaCelda();
            }
            jlblFila.setText("Fila: " + (MetodoSimplex.filaMenor - 1));
            jlblColumna.setText("Columna: " + (MetodoSimplex.columnaMayor));
            jlblPivote.setText("Pivote: " + AproximarNumero.valorAproximado(String.valueOf
        (modSolu.getValueAt(MetodoSimplex.filaMenor, MetodoSimplex.columnaMayor))));
    }//GEN-LAST:event_Click

    private void tablaRestricciones(){
        iX = Integer.parseInt(String.valueOf(jspVar.getValue()));
        iNoRest = Integer.parseInt(String.valueOf(jspRest.getValue()));
        Object oCabeza[] = new String[iX + 3];
        oCabeza[0] = ("");
        for(int i = 1; i <= iX; i++) {
            oCabeza[i] = ("X" + i);
        }
        oCabeza[iX + 1] = ("");
        oCabeza[iX + 2] = ("");
        modRest = new DefaultTableModel(oCabeza, 0){
            public boolean isCellEditable(int row, int column){
                if(column == 0)
                    return false;
                if(row == 0 && column >= modRest.getColumnCount() - 2)
                    return false;
                return true;
            }
        };
        jtblRest.setModel(modRest);
        String row[] = new String[iX + 3];
        for (int i = 0; i < iNoRest + 1; i++){
            if (i == 0)
                row[0] = new String("     Z =");
            else{
                row[0] = new String("Rest. " + (i));
                row[modRest.getColumnCount() - 2] = "<=";
            }
            modRest.addRow(row);
        }
        agregarOpciones(modRest.getColumnCount(), jtblRest);
    }
    private void ecuaciones(){
        jtxtarModMat.setText(null);
        int row = modRest.getRowCount();
        int column = modRest.getColumnCount();
        jtxtarModMat.append(" Z = ");
        for(int i = 1; i <column-2; i++) {
            if(Double.parseDouble(String.valueOf(modRest.getValueAt(0, i))) >= 0) 
                jtxtarModMat.append(" +" + " " + modRest.getValueAt(0, i) + "X" + i);
            else
                jtxtarModMat.append(" " + modRest.getValueAt(0, i) + " X" + i);
        }
        jtxtarModMat.append(" \n\n");
        for(int i = 1; i < row; i++) {
            jtxtarModMat.append(" ");
            for(int j = 1; j < column; j++){
                if(j == 1)
                    jtxtarModMat.append("" + modRest.getValueAt(i, j) + "X" + j);
                else if(j == column - 2)
                    jtxtarModMat.append(" " + modRest.getValueAt(i, j));
                else{
                    if(j >= column - 2)
                        jtxtarModMat.append(" " + modRest.getValueAt(i, j));
                    else{
                        if(Double.parseDouble(String.valueOf(modRest.getValueAt(i, j))) >= 0)
                            jtxtarModMat.append(" +" + " " + modRest.getValueAt(i, j) + "X" + j);
                        else
                            jtxtarModMat.append(" " + modRest.getValueAt(i, j) + " X" + j);
                    }
                }
            }
            jtxtarModMat.append("\n");
        }
    }
    private void agregarOpciones(int a, JTable jtRest){
        String[] Condicion = {"<=", ">=", "=",">","<"};
        JComboBox jcb = new JComboBox(Condicion);
        TableColumn tc = jtRest.getColumnModel().getColumn(a - 2);
        TableCellEditor tce = new DefaultCellEditor(jcb);
        tc.setCellEditor(tce);
        jtRest.getColumnModel().getColumn(0).setPreferredWidth(50);
        jtRest.getColumnModel().getColumn(a - 1).setPreferredWidth(80);
        jtRest.getColumnModel().getColumn(a - 2).setPreferredWidth(30);
        for (int i = 1; i <= a - 2; i++){
            jtRest.getColumnModel().getColumn(0).setPreferredWidth(80);
        }
        jtRest.setRowHeight(25);
    }
    private boolean validar() {
        String texto;
        int row = modRest.getRowCount();
        int column = modRest.getColumnCount();
        for(int i = 0; i < row; i++){
            for(int j = 1; j < column; j++){
                if(i == 0 && j >= column - 2)
                    break;
                else if(j != column - 2){
                    texto = String.valueOf(modRest.getValueAt(i, j));
                    if (!texto.matches("([+-]{1})?[0-9]+(\\.[0-9]+)?([Ee]{1}([-]{1})?[1-9])?")) {
                        JOptionPane.showMessageDialog(this, "Faltan o hay datos incorrectos,\nasegúrese de no escribir espacios en \nblanco o los decimales con coma.");
                        return true;
                    }
                }
            }
        }
        return false;
    }
    public void limpiarUltimaCelda(){
        for(int i = 0; i < jtblTabla.getRowCount(); i++) {
            jtblTabla.setValueAt("", i, jtblTabla.getColumnCount()-1);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MSimplex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MSimplex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MSimplex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MSimplex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MSimplex().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame Datos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton jbtnContinuar;
    private javax.swing.JButton jbtnInDat;
    private javax.swing.JButton jbtnInicio;
    private javax.swing.JButton jbtnOk;
    private javax.swing.JButton jbtnSalir;
    private javax.swing.JButton jbtnSolPasoAPaso;
    private javax.swing.JButton jbtnSolucion;
    private javax.swing.JComboBox<String> jcbMaxMin;
    private javax.swing.JLabel jlblColumna;
    private javax.swing.JLabel jlblFila;
    private javax.swing.JLabel jlblModMat;
    private javax.swing.JLabel jlblPivote;
    private javax.swing.JSpinner jspRest;
    private javax.swing.JSpinner jspVar;
    public static javax.swing.JTextArea jtaOp;
    private javax.swing.JTable jtblRest;
    private javax.swing.JTable jtblTabla;
    private javax.swing.JTextArea jtxtarModMat;
    // End of variables declaration//GEN-END:variables
}
