/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import OrigenDestino.Datos;
import OrigenDestino.EsquinaNorOeste;
import OrigenDestino.GuardarOrigenDestino;
import Tablas.TablaOrigenDestino;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author EdithGmz
 */

/* Había un error en la tabla de asignación de datos al momento de dar clic en el botón "CONTINUAR" para poder
    continuar se debe deseleccionar la tabla y luego dar click en el botón.
 * Otro error se encontraba al momento de dar clic en el botón "SOLUCIONAR" para arreglarlo se realizaron algunos
    cambios en la clase "EsquinaNorOeste" en la variable iFila, el error se encontraba en iFila = dDatos[0].length,
    lo correcto es iFila = dDatos.length */

public class OrigenDestino extends javax.swing.JFrame {
    
public static int iDest;
public static int iOri;
public static DefaultTableModel modRest = null;
private DefaultTableModel modSol = null;
public static Datos dDatos[][];
TablaOrigenDestino tod = new TablaOrigenDestino();
EsquinaNorOeste ENO;
public static int iFilaExtra = 0;
public static int iColumnaExtra = 0;
public boolean bFilaFicticia = false;
public boolean bColumnaFicticia = false;
double dDemanda = 0.0;
double dOferta = 0.0;
public static boolean bCorte = true;
public static String sNoRep;
boolean bGuardar;
GuardarOrigenDestino guardar;

        
    /**
     * Creates new form OrigenDestino
     */
    public OrigenDestino() {
        initComponents();
        
        jtblSolu.setRowHeight(50);
        jtblRest.setRowHeight(25);
        jtblDatos.setRowHeight(22);
        iDest = Integer.parseInt("" + jspDest.getValue());
        iOri = Integer.parseInt("" + jspOri.getValue());
        new TablaOrigenDestino().tablaRestricciones(iDest, iOri, jtblRest, 0);
        JTableHeader jtHead;
        jtHead = jtblRest.getTableHeader();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Datos = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jcbMetodos = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jspDest = new javax.swing.JSpinner();
        jspOri = new javax.swing.JSpinner();
        jbtnOkSp = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jckbPlanFict = new javax.swing.JCheckBox();
        jckbDestFict = new javax.swing.JCheckBox();
        jbtnOkFict = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblRest = new javax.swing.JTable();
        jbtnContinuar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtblSolu = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtblDatos = new javax.swing.JTable();
        jlblZ = new javax.swing.JLabel();
        jlblValorZ = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jbtnInDat = new javax.swing.JButton();
        jbtnSolucion = new javax.swing.JButton();
        jbtnSolPasoAPaso = new javax.swing.JButton();
        jbtnSalir = new javax.swing.JButton();
        jbtnInicio = new javax.swing.JButton();

        jcbMetodos.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jcbMetodos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Esquina Noroeste", "Costo Mínimo", "Vogel" }));
        jcbMetodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbMetodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcbMetodos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jcbMetodos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabel1.setText("Destino");

        jLabel2.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabel2.setText("Origen");

        jspDest.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N

        jspOri.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jspOri.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jspOriStateChanged(evt);
            }
        });

        jbtnOkSp.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        jbtnOkSp.setText("OK");
        jbtnOkSp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OnClick(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jspDest, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                    .addComponent(jspOri))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnOkSp)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jspDest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jspOri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnOkSp))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ficticio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gadugi", 1, 14))); // NOI18N

        jckbPlanFict.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        jckbPlanFict.setText("Planta");
        jckbPlanFict.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jckbPlanFictActionPerformed(evt);
            }
        });

        jckbDestFict.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        jckbDestFict.setText("Destino");
        jckbDestFict.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jckbDestFictActionPerformed(evt);
            }
        });

        jbtnOkFict.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jbtnOkFict.setText("OK");
        jbtnOkFict.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OnClick(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jckbDestFict)
                        .addGap(10, 10, 10)
                        .addComponent(jbtnOkFict))
                    .addComponent(jckbPlanFict)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jckbPlanFict)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jckbDestFict)
                    .addComponent(jbtnOkFict))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, Short.MAX_VALUE)))
        );

        jPanel7.getAccessibleContext().setAccessibleDescription("");

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gadugi", 1, 14))); // NOI18N

        jtblRest.setFont(new java.awt.Font("Gadugi", 0, 14)); // NOI18N
        jtblRest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Origen 1", null, null, null, null},
                {"Origen 2", null, null, null, null},
                {"Origen 3", null, null, null, null},
                {"Demanda", null, null, null, null}
            },
            new String [] {
                "", "Destino 1", "Destino 2", "Destino 3", "Oferta"
            }
        ));
        jtblRest.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtblRestKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jtblRest);

        jbtnContinuar.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jbtnContinuar.setText("CONTINUAR");
        jbtnContinuar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OnClick(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbtnContinuar)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnContinuar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout DatosLayout = new javax.swing.GroupLayout(Datos.getContentPane());
        Datos.getContentPane().setLayout(DatosLayout);
        DatosLayout.setHorizontalGroup(
            DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DatosLayout.setVerticalGroup(
            DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jtblSolu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jtblSolu);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
                .addContainerGap())
        );

        jtblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Origen", "Destino", "Productos", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jtblDatos);

        jlblZ.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jlblZ.setText("Z = ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlblZ, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlblValorZ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblZ, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblValorZ, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jbtnInDat.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jbtnInDat.setText("INSERTAR DATOS");
        jbtnInDat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OnClick(evt);
            }
        });

        jbtnSolucion.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jbtnSolucion.setText("SOLUCIÓN");
        jbtnSolucion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OnClick(evt);
            }
        });

        jbtnSolPasoAPaso.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jbtnSolPasoAPaso.setText("SOLUCIÓN PASO A PASO");
        jbtnSolPasoAPaso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OnClick(evt);
            }
        });

        jbtnSalir.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jbtnSalir.setText("SALIR");
        jbtnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OnClick(evt);
            }
        });

        jbtnInicio.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jbtnInicio.setText("INICIO");
        jbtnInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OnClick(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jbtnInDat, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jbtnSolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jbtnSolPasoAPaso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnSolucion)
                    .addComponent(jbtnInDat)
                    .addComponent(jbtnSolPasoAPaso)
                    .addComponent(jbtnSalir)
                    .addComponent(jbtnInicio))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OnClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OnClick
        if(evt.getSource() == jbtnInDat){
            Datos.setVisible(true);
        } else if(evt.getSource() == jbtnInicio){
            new Inicio().setVisible(true);
            this.dispose();
        } else if(evt.getSource() == jbtnSalir)
            System.exit(0);
        else if(evt.getSource() == jbtnContinuar){
            boolean resp = equilibrar();
            if(isNumeric(jtblRest) && resp){
                iDest = Integer.parseInt(""+jspDest.getValue());
                iOri = Integer.parseInt(""+jspOri.getValue());
                tod.tablaSolucion(jtblRest, jtblSolu,iFilaExtra,iColumnaExtra);
                if(jcbMetodos.getSelectedIndex() == 0){
                    ENO = new EsquinaNorOeste();
                    ENO.calcularDemandaOfertaTotal(jtblSolu, 0, 0);
                }
                jbtnSolucion.setEnabled(true);
                jbtnSolPasoAPaso.setEnabled(true);
                Datos.setVisible(false);
            }
        } else if(evt.getSource() == jbtnOkSp){
            iDest = Integer.parseInt("" + jspDest.getValue());
            iOri = Integer.parseInt("" + jspOri.getValue());
            new TablaOrigenDestino().tablaRestricciones(iDest, iOri, jtblRest,0);
            jckbPlanFict.setSelected(false);
            jckbDestFict.setSelected(false);
            bColumnaFicticia= false;
            bFilaFicticia = false;
        } else if(evt.getSource() == jbtnSolPasoAPaso){
            if(jcbMetodos.getSelectedIndex() == 0){
                if(ENO.noroeste(jtblSolu, modSol)){
                    enviar();
                    jbtnSolPasoAPaso.setEnabled(false);
                }
                jtblSolu.setValueAt("", 0,0);
            }
            jlblValorZ.setText(""+calcularTotal());
        } else if(evt.getSource() == jbtnSolucion){
            boolean fin = false;
            bCorte = false;
            while(!fin){
                if(jcbMetodos.getSelectedIndex() == 0){
                    if(ENO.noroeste(jtblSolu, modSol)){
                        enviar();
                        jbtnSolucion.setEnabled(false);
                        jbtnSolPasoAPaso.setEnabled(false);
                        fin = true;
                    }
                    jtblSolu.setValueAt("", 0,0);
                }
            }
            jlblValorZ.setText(""+calcularTotal());
        } else if(evt.getSource() == jbtnOkFict){
            if(bColumnaFicticia){
                calcularDemandaOfertaTotal(jtblRest, 0, 1);
                modRest.setValueAt((dOferta - dDemanda), modRest.getRowCount()-1,
                        modRest.getColumnCount()-2);
            } else if (bFilaFicticia){
                calcularDemandaOfertaTotal(jtblRest, 1, 0);
                modRest.setValueAt((dOferta - dDemanda), modRest.getRowCount()-2,
                        modRest.getColumnCount()-1);
            } else
                calcularDemandaOfertaTotal(jtblRest, 0, 0);
            if(dOferta == dDemanda){
                if(bFilaFicticia){
                    eliminaFila();
                    bFilaFicticia = false;
                    jckbPlanFict.setSelected(false);
                } else if(bColumnaFicticia){
                    eliminarColumna();
                    bColumnaFicticia = false;
                    jckbDestFict.setSelected(false);
                }
            }
            else if(dOferta!= dDemanda){
                if(dOferta > dDemanda && bFilaFicticia){
                    eliminaFila();
                    bFilaFicticia = false;
                    jckbPlanFict.setSelected(false);
                    agregarColumna();
                    bColumnaFicticia = true;
                    jckbDestFict.setSelected(true);
                } else if(dOferta < dDemanda && bColumnaFicticia){
                    eliminarColumna();
                    bColumnaFicticia = false;
                    jckbDestFict.setSelected(false);
                    agregarFila();
                    bFilaFicticia = true;
                    jckbPlanFict.setSelected(true);
                }
            }
            if(!bColumnaFicticia && !bFilaFicticia){
                if(dOferta < dDemanda){
                    agregarFila();
                    bFilaFicticia = true;
                    jckbPlanFict.setSelected(true);
                }
                else  if(dOferta > dDemanda){
                    agregarColumna();
                    bColumnaFicticia= true;
                    jckbDestFict.setSelected(true);
                }
            }
        }
    }//GEN-LAST:event_OnClick

    private void jtblRestKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtblRestKeyTyped
        char a = evt.getKeyChar();
        if(!Character.isDigit(a) && a != '-' && a != 'E' && a != '.')
            evt.consume();
    }//GEN-LAST:event_jtblRestKeyTyped

    private void jspOriStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jspOriStateChanged
        int fila = Integer.parseInt(jspOri.getValue().toString());
        String g[] = new String[iDest];
        if (fila > iOri) {
            for (int i = iOri + 1; i <= fila; i++){
                //g[0] = "Demanda " + i;
                modRest.addRow(g);
                String tem;
                for (int j = 0; j < modRest.getColumnCount(); j++){
                    tem = ""+modRest.getValueAt(modRest.getRowCount()-2, j);
                    if(!tem.equals("null"))
                        modRest.setValueAt(tem, modRest.getRowCount()-1, j);
                    modRest.setValueAt("", modRest.getRowCount()-2, j);
                }
                modRest.setValueAt("Origen "+i, modRest.getRowCount()-2, 0);
                modRest.setValueAt("", modRest.getRowCount()-1, modRest.getColumnCount()-1);
            }
            iOri = fila;
        } else if (fila < iOri){
            while (iOri != fila){
                modRest.removeRow(iOri - 1);
                iOri--;
            }
        }
    }//GEN-LAST:event_jspOriStateChanged

    private void jcbMetodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMetodosActionPerformed
        sNoRep =null;
        if(jcbMetodos.getSelectedIndex() == 0){
            iFilaExtra = 0 ;
            iColumnaExtra = 0 ;
        }
        jbtnSolucion.setEnabled(false);
        jbtnSolPasoAPaso.setEnabled(false);
    }//GEN-LAST:event_jcbMetodosActionPerformed

    private void jckbPlanFictActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jckbPlanFictActionPerformed
        if(jckbDestFict.isSelected())
            eliminarColumna();
        calcularDemandaOfertaTotal(jtblSolu, 0, 0);
        jckbDestFict.setSelected(false);
        if(!jckbPlanFict.isSelected())
            eliminaFila();
        else
            agregarFila();
    }//GEN-LAST:event_jckbPlanFictActionPerformed

    private void jckbDestFictActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jckbDestFictActionPerformed
        if(jckbPlanFict.isSelected())
            eliminaFila();
        calcularDemandaOfertaTotal(jtblRest, 0, 0);
        jckbPlanFict.setSelected(false);
        if(!jckbDestFict.isSelected())
            eliminarColumna();
        else
            agregarColumna();        
    }//GEN-LAST:event_jckbDestFictActionPerformed

    public boolean equilibrar(){
        if(bColumnaFicticia)
            calcularDemandaOfertaTotal(jtblRest, 0, 1);
        else if (bFilaFicticia)
            calcularDemandaOfertaTotal(jtblRest, 1, 0);
        else calcularDemandaOfertaTotal(jtblRest, 0, 0);
        if(dOferta == dDemanda){
            if(bFilaFicticia)
                return false;
            else if(bColumnaFicticia)
                return false;
        } else if(dOferta != dDemanda){
            if(dOferta > dDemanda && bFilaFicticia)
                return false;
            else  if(dOferta < dDemanda && bColumnaFicticia)
                return false;
        }
        if(!bColumnaFicticia && !bFilaFicticia){
            if(dOferta < dDemanda)
                return false;
            else  if(dOferta > dDemanda)
                return false;
        }
        return true;
    }
    public void agregarColumna(){
        bColumnaFicticia = true;
        modRest.addColumn("Oferta");
        renombrarColumna("Ficticio", jtblRest);
        moverDatos(jtblRest);
        modRest.setValueAt((dOferta - dDemanda), modRest.getRowCount()-1, modRest.getColumnCount()-2);
    }
    public void eliminarColumna(){
        bColumnaFicticia = false;
        String tem[][] = extraer(jtblRest, 1);
        new TablaOrigenDestino().tablaRestricciones(iDest, iOri, jtblRest,0);
        for (int i = 0; i < tem.length; i++){
            for (int j = 1; j < tem[i].length; j++){
                modRest.setValueAt(tem[i][j], i, j);
            }
        } 
    }
    public void agregarFila(){
        bFilaFicticia = true;
        String temp;
        modRest.addRow(new String[]{"Demanda"});
        int p = modRest.getRowCount();
        for (int i = 0; i < modRest.getColumnCount(); i++){
            temp =" "+modRest.getValueAt(p-2, i);
            if(String.valueOf(modRest.getValueAt(p-2, i)).equalsIgnoreCase("null"))
                temp=" ";
            modRest.setValueAt(temp, p-1, i);
            if(i == 0)
                modRest.setValueAt("Ficticio", p-2, i);
            else
                modRest.setValueAt("0", p-2, i);
        }
        modRest.setValueAt((dDemanda - dOferta), modRest.getRowCount()-2, modRest.getColumnCount()-1);
    }
    public void eliminaFila(){
        bFilaFicticia = false;
        modRest.removeRow(modRest.getRowCount()-2); 
    }
    public void renombrarColumna(String n, JTable table){
            JTableHeader th=table.getTableHeader();
            TableColumnModel tcm=th.getColumnModel();
            TableColumn tc=tcm.getColumn(table.getColumnCount()-2);
            tc.setHeaderValue("Ficticio");
            th.repaint(); 
    }
    public void moverDatos(JTable table){
        for (int i = 0; i < table.getRowCount()-1; i++){
            table.setValueAt(table.getValueAt(i, table.getColumnCount()-2), i,  table.getColumnCount()-1);
            table.setValueAt(0, i, table.getColumnCount()-2);
        }
    }
    public String[][] extraer(JTable table, int a){
        String t[][] = new String[table.getRowCount()][table.getColumnCount()-a];
        for(int i = 0; i < table.getRowCount(); i++){
            for(int j = 0; j < table.getColumnCount()-2; j++){
                if(String.valueOf(table.getValueAt(i, j)).equalsIgnoreCase("null"))
                    t[i][j] = " ";
                else
                    t[i][j] = " " + table.getValueAt(i, j);
            }
        }
        int p = table.getColumnCount();
        for(int i = 0; i < table.getRowCount()-1; i++){
            if(String.valueOf(table.getValueAt(i, p-1)).equalsIgnoreCase("null"))
                t[i][p-a-1] = " ";
            else
                t[i][p-a-1] = " " + table.getValueAt(i, p-1);
        }
        return t;
    }
    public void calcularDemandaOfertaTotal(JTable jtSolucion, int filaExtra, int columnaExtra){
        dDemanda = 0.0;
        dOferta = 0.0;
        for(int i = 1; i < (jtblRest.getColumnCount() - 1 - columnaExtra); i++){
            try{
                dDemanda = dDemanda + Double.parseDouble("" + jtblRest.getValueAt(jtblRest.getRowCount()-1, i));
            } catch(Exception e){}
        }
        for(int i = 0; i < (jtblRest.getRowCount() - 1 - filaExtra); i++){
            try{
                dOferta = dOferta + Double.parseDouble("" + jtblRest.getValueAt(i, jtblRest.getColumnCount()-1));
            } catch(Exception e){}
        }
    }
    private boolean isNumeric(JTable table){
        for (int i = 0; i <table.getRowCount() ; i++){
            for (int j = 1; j < table.getColumnCount(); j++){
                try{
                    if(i == table.getRowCount()-1 && j == table.getColumnCount()-1 )
                        return true;
                    if(i == table.getRowCount()-1 || j == table.getColumnCount()-1 )
                        Double.parseDouble("" + table.getValueAt(i, j));
                    else if(!"-".equals("" + table.getValueAt(i, j)))
                        Double.parseDouble("" + table.getValueAt(i, j));
                } catch(Exception e){
                    return false;
                }
            }
        }
        return true;
    }
  public void enviar(){
      Object[] oCabeza = {"Origen","Destino","Material","Precio","Subtotal"};
      DefaultTableModel mode = new DefaultTableModel(oCabeza,0){
          public boolean isCellEditable(int row, int column){
              return false;
          }
      };
      String row[] = new String[5];
      for (int i = 0; i < dDatos.length; i++) {
          for (int j = 0; j < dDatos[0].length; j++) {
              if(dDatos[i][j].getCant() > 0D){
                  row[0]= " " + (i+1);
                  row[1]= " " + (j+1);
                  row[2]= " " + dDatos[i][j].getCant();
                  row[3]= " " + dDatos[i][j].getPrecio();
                  row[4]= " " + dDatos[i][j].getCant() * Double.parseDouble(dDatos[i][j].getPrecio());
                  mode.addRow(row);
              }
          }
      }
      jtblDatos.setModel(mode);
  }
 double calcularTotal(){
     double dTotal = 0;
     for (int i = 0; i < dDatos.length; i++){
         for (int j = 0; j < dDatos[i].length; j++){
             if(!dDatos[i][j].getPrecio().equalsIgnoreCase("-")){
                 dTotal = dTotal + Double.parseDouble(dDatos[i][j].getPrecio()) * dDatos[i][j].getCant();
             }
         }
     }
     return dTotal;
 }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrigenDestino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrigenDestino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrigenDestino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrigenDestino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrigenDestino().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame Datos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbtnContinuar;
    private javax.swing.JButton jbtnInDat;
    private javax.swing.JButton jbtnInicio;
    private javax.swing.JButton jbtnOkFict;
    private javax.swing.JButton jbtnOkSp;
    private javax.swing.JButton jbtnSalir;
    private javax.swing.JButton jbtnSolPasoAPaso;
    private javax.swing.JButton jbtnSolucion;
    private javax.swing.JComboBox<String> jcbMetodos;
    private javax.swing.JCheckBox jckbDestFict;
    private javax.swing.JCheckBox jckbPlanFict;
    private javax.swing.JLabel jlblValorZ;
    private javax.swing.JLabel jlblZ;
    private javax.swing.JSpinner jspDest;
    private javax.swing.JSpinner jspOri;
    private javax.swing.JTable jtblDatos;
    private javax.swing.JTable jtblRest;
    private javax.swing.JTable jtblSolu;
    // End of variables declaration//GEN-END:variables
}
